SIM = verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)
export PYTHONPATH:=$(PWD)/systolicarray_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mkSystolicArray.v

EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mkSystolicArray
MODULE = test_systolic_array_int8

include $(shell cocotb-config --makefiles)/Makefile.sim
